name: Bug report
description: Create a report to help us solve a bug
title: '[Bug]: An explicit title'
labels: bug
assignees: l3alr0g
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened ?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: How can we reproduce it ?
      description: Steps to reproduce the behavior
      placeholder: Go to settings, click on ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our Slashboard are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/l3alr0g/Slashboard-desktop/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
